### ISSUE TITLE
Alice's agent crashes after invitation

### ISSUE THREAD

**Issue by arjanvaneersel** [cloudcompass/ToIPLabs#49]
I use playwithvon to run this lab (as a part of the EDX course). 

However, when entering the invitation into Alice's agent, the agent crashes. Here's what happens:

```
#9 Input faber.py invitation details
WARNING: your terminal doesn't support cursor position requests (CPR).
Invite details: {"@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/connections/1.0/invitation", "@id": "e276be5b-995e-4bb9-a11b-9a8be8a305e2",
 "label": "faber.agent", "serviceEndpoint": "http://ip10-2-199-5-c323kdep86g0a7b5n340-8020.direct.play-with-von.vonx.io", "recipientKeys":
 ["8vMubZdJoiWs4oNmHSB5HvPou7vnosz7QSGPjHk7TX7w"]}                                                                                        
alice.agent handle_connections invitation invitation-received
alice.agent set connection id 67b14103-70f2-4785-b5e3-1f66e1380460
alice.agent handle_connections request request-sent
Invitation response:
  {
    "invitation_key": "8vMubZdJoiWs4oNmHSB5HvPou7vnosz7QSGPjHk7TX7w",
    "accept": "auto",
    "updated_at": "2021-06-12 04:54:04.988710Z",
    "their_role": "inviter",
    "invitation_mode": "once",
    "connection_id": "67b14103-70f2-4785-b5e3-1f66e1380460",
    "request_id": "475558c1-f1f0-415f-8e70-f5486a853320",
    "their_label": "faber.agent",
    "routing_state": "none",
    "state": "request",
    "rfc23_state": "request-sent",
    "my_did": "AMTeBcUYoY4F83AGGhEY6C",
    "created_at": "2021-06-12 04:54:04.943958Z"
  }
  
Connect duration: 0.12s
Waiting for connection...
Alice      | 2021-06-12 04:54:17,399 aries_cloudagent.transport.outbound.manager ERROR >>> Error when posting to: http://ip10-2-199-5-c323kdep86g0a7b5n340-8020.direct.play-with-von.vonx.io; Error: (<class 'aries_cloudagent.transport.outbound.base.OutboundTransportError'>, OutboundTransportError('Unexpected response status 503, caused by: Service Unavailable',), <traceback object at 0x7f2d46e8b0c8>); Re-queue failed message ...
Alice      | 2021-06-12 04:54:39,768 aries_cloudagent.transport.outbound.manager ERROR >>> Error when posting to: http://ip10-2-199-5-c323kdep86g0a7b5n340-8020.direct.play-with-von.vonx.io; Error: (<class 'aries_cloudagent.transport.outbound.base.OutboundTransportError'>, OutboundTransportError('Unexpected response status 503, caused by: Service Unavailable',), <traceback object at 0x7f2d46e8bb88>); Re-queue failed message ...
Alice      | 2021-06-12 04:55:02,072 aries_cloudagent.transport.outbound.manager ERROR >>> Error when posting to: http://ip10-2-199-5-c323kdep86g0a7b5n340-8020.direct.play-with-von.vonx.io; Error: (<class 'aries_cloudagent.transport.outbound.base.OutboundTransportError'>, OutboundTransportError('Unexpected response status 503, caused by: Service Unavailable',), <traceback object at 0x7f2d46e8be88>); Re-queue failed message ...
Alice      | 2021-06-12 04:55:24,440 aries_cloudagent.transport.outbound.manager ERROR >>> Error when posting to: http://ip10-2-199-5-c323kdep86g0a7b5n340-8020.direct.play-with-von.vonx.io; Error: (<class 'aries_cloudagent.transport.outbound.base.OutboundTransportError'>, OutboundTransportError('Unexpected response status 503, caused by: Service Unavailable',), <traceback object at 0x7f2d46e8bb88>); Re-queue failed message ...
Alice      | 2021-06-12 04:55:46,775 aries_cloudagent.transport.outbound.manager ERROR >>> Outbound message failed to deliver, NOT Re-queued.
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/aries_cloudagent/transport/outbound/http.py", line 86, in handle_message
Alice      |     f"Unexpected response status {response.status}, "
Alice      | aries_cloudagent.transport.outbound.base.OutboundTransportError: Unexpected response status 503, caused by: Service Unavailable
Alice      | 2021-06-12 04:55:46,777 aries_cloudagent.transport.outbound.manager ERROR Outbound message could not be delivered to http://ip10-2-199-5-c323kdep86g0a7b5n340-8020.direct.play-with-von.vonx.io
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/aries_cloudagent/transport/outbound/http.py", line 86, in handle_message
Alice      |     f"Unexpected response status {response.status}, "
Alice      | aries_cloudagent.transport.outbound.base.OutboundTransportError: Unexpected response status 503, caused by: Service Unavailable
``` 

Am I doing something wrong or is this a bug?

**Comment by swcurran** [comment]
Investigating this -- I'm getting the same result.  We have issues from time to time with Play with VON, so it might be the underlying platform.

More to come.

**Comment by swcurran** [comment]
Should be working now -- we restarted the Play with VON site.

**Comment by swcurran** [comment]
Confirmed it is working.  There was a problem with networking on the platform, which matches the symptoms.

Closing this issue.
