### ISSUE TITLE
Lab LFS172x/agentbook-acapy.md does not work anymore

### ISSUE THREAD

**Issue by ilmirajat** [cloudcompass/ToIPLabs#84]
I tried to follow both steps in video https://www.youtube.com/watch?v=He1QHYuYxlw and in doc/LFS172x/agentbook-acapy.md 

1. When I tried to run lab in play-with-docker I got error that indicated insufficient storage (no space left on device). 

2. I noticed that in video http://play-with-von.vonx.io I tried it. 

I managed to get agent up and running. However, after pasting invitation I got 400 Bad Request error. 

Here is full console log from play-with-von:

```
###############################################################
#                          WARNING!!!!                        #
# This is a sandbox environment. Using personal credentials   #
# is HIGHLY! discouraged. Any consequences of doing so are    #
# completely the user's responsibilites.                      #
#                                                             #
# The PWD team.                                               #
###############################################################
[node1] (local) root@10.2.63.4 ~
$ git clone https://github.com/hyperledger/aries-cloudagent-python
Cloning into 'aries-cloudagent-python'...
remote: Enumerating objects: 47305, done.
remote: Counting objects: 100% (2875/2875), done.
remote: Compressing objects: 100% (1092/1092), done.
remote: Total 47305 (delta 1925), reused 2596 (delta 1774), pack-reused 44430
Receiving objects: 100% (47305/47305), 37.77 MiB | 15.06 MiB/s, done.
Resolving deltas: 100% (35139/35139), done.
[node1] (local) root@10.2.63.4 ~
$ cd aries-cloudagent-python/demo/
[node1] (local) root@10.2.63.4 ~/aries-cloudagent-python/demo
$ LEDGER_URL=http://dev.bcovrin.vonx.io ./run_demo alice
Preparing agent image...
sha256:6fa5673be3e3969e5fbfb23db483d0d93d630e0d61046517baa77324b20bbb61
ip10-2-63-4-c50v5b9da8909vr6b89g-{PORT}.direct.play-with-von.vonx.io
Starting [alice] agent with args [--port 8030]
Initializing demo agent alice with AIP 20 and credential type None

#7 Provision an agent and wallet, get back configuration details
Alice      | ['/home/indy/.pyenv/versions/3.6.13/bin/python', '-m', 'aries_cloudagent', 'start', '--endpoint', 'http://ip10-2-63-4-c50v5b9da8909vr6b89g-8030.direct.play-with-von.vonx.io', '--label', 'alice.agent', '--auto-ping-connection', '--auto-respond-messages', '--inbound-transport', 'http', '0.0.0.0', '8030', '--outbound-transport', 'http', '--admin', '0.0.0.0', '8031', '--admin-insecure-mode', '--wallet-type', 'indy', '--wallet-name', 'alice.agent129981', '--wallet-key', 'alice.agent129981', '--preserve-exchange-records', '--auto-provision', '--emit-new-didcomm-prefix', '--genesis-transactions', '{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node1","blskey":"4N8aUNHSgjQVgkpm8nhNEfDf6txHznoYREg9kirmJrkivgL4oSEimFF6nsQ6M41QvhM2Z33nves5vfSn9n1UwNFJBYtWVnHYMATn76vLuL3zU88KyeAYcHfsih3He6UHcXDxcaecHVz6jhCYz1P2UZn2bDVruL5wXpehgBfBaLKm3Ba","blskey_pop":"RahHYiCvoNCtPTrVtP7nMC5eTYrsUA8WjXbdhNc8debh1agE9bGiJxWBXYNFbnJXoXhWFMvyqhqhRoq737YQemH5ik9oL7R4NTTCz2LEZhkgLJzB3QRQqJyBNyv7acbdHrAT8nQ9UkLbaVL9NBpnWXBTw4LEMePaSHEw66RzPNdAX1","client_ip":"159.89.115.24","client_port":9702,"node_ip":"159.89.115.24","node_port":9701,"services":["VALIDATOR"]},"dest":"Gw6pDLhcBcoQesN72qfotTgFa7cbuqZpkX3Xo6pLhPhv"},"metadata":{"from":"Th7MpTaRZVRYnPiabds81Y"},"type":"0"},"txnMetadata":{"seqNo":1,"txnId":"fea82e10e894419fe2bea7d96296a6d46f50f93f9eeda954ec461b2ed2950b62"},"ver":"1"}\n{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node2","blskey":"37rAPpXVoxzKhz7d9gkUe52XuXryuLXoM6P6LbWDB7LSbG62Lsb33sfG7zqS8TK1MXwuCHj1FKNzVpsnafmqLG1vXN88rt38mNFs9TENzm4QHdBzsvCuoBnPH7rpYYDo9DZNJePaDvRvqJKByCabubJz3XXKbEeshzpz4Ma5QYpJqjk","blskey_pop":"Qr658mWZ2YC8JXGXwMDQTzuZCWF7NK9EwxphGmcBvCh6ybUuLxbG65nsX4JvD4SPNtkJ2w9ug1yLTj6fgmuDg41TgECXjLCij3RMsV8CwewBVgVN67wsA45DFWvqvLtu4rjNnE9JbdFTc1Z4WCPA3Xan44K1HoHAq9EVeaRYs8zoF5","client_ip":"159.89.115.24","client_port":9704,"node_ip":"159.89.115.24","node_port":9703,"services":["VALIDATOR"]},"dest":"8ECVSk179mjsjKRLWiQtssMLgp6EPhWXtaYyStWPSGAb"},"metadata":{"from":"EbP4aYNeTHL6q385GuVpRV"},"type":"0"},"txnMetadata":{"seqNo":2,"txnId":"1ac8aece2a18ced660fef8694b61aac3af08ba875ce3026a160acbc3a3af35fc"},"ver":"1"}\n{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node3","blskey":"3WFpdbg7C5cnLYZwFZevJqhubkFALBfCBBok15GdrKMUhUjGsk3jV6QKj6MZgEubF7oqCafxNdkm7eswgA4sdKTRc82tLGzZBd6vNqU8dupzup6uYUf32KTHTPQbuUM8Yk4QFXjEf2Usu2TJcNkdgpyeUSX42u5LqdDDpNSWUK5deC5","blskey_pop":"QwDeb2CkNSx6r8QC8vGQK3GRv7Yndn84TGNijX8YXHPiagXajyfTjoR87rXUu4G4QLk2cF8NNyqWiYMus1623dELWwx57rLCFqGh7N4ZRbGDRP4fnVcaKg1BcUxQ866Ven4gw8y4N56S5HzxXNBZtLYmhGHvDtk6PFkFwCvxYrNYjh","client_ip":"159.89.115.24","client_port":9706,"node_ip":"159.89.115.24","node_port":9705,"services":["VALIDATOR"]},"dest":"DKVxG2fXXTU8yT5N7hGEbXB3dfdAnYv1JczDUHpmDxya"},"metadata":{"from":"4cU41vWW82ArfxJxHkzXPG"},"type":"0"},"txnMetadata":{"seqNo":3,"txnId":"7e9f355dffa78ed24668f0e0e369fd8c224076571c51e2ea8be5f26479edebe4"},"ver":"1"}\n{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node4","blskey":"2zN3bHM1m4rLz54MJHYSwvqzPchYp8jkHswveCLAEJVcX6Mm1wHQD1SkPYMzUDTZvWvhuE6VNAkK3KxVeEmsanSmvjVkReDeBEMxeDaayjcZjFGPydyey1qxBHmTvAnBKoPydvuTAqx5f7YNNRAdeLmUi99gERUU7TD8KfAa6MpQ9bw","blskey_pop":"RPLagxaR5xdimFzwmzYnz4ZhWtYQEj8iR5ZU53T2gitPCyCHQneUn2Huc4oeLd2B2HzkGnjAff4hWTJT6C7qHYB1Mv2wU5iHHGFWkhnTX9WsEAbunJCV2qcaXScKj4tTfvdDKfLiVuU2av6hbsMztirRze7LvYBkRHV3tGwyCptsrP","client_ip":"159.89.115.24","client_port":9708,"node_ip":"159.89.115.24","node_port":9707,"services":["VALIDATOR"]},"dest":"4PS3EDQ3dW1tci1Bp6543CfuuebjFrg36kLAUcskGfaA"},"metadata":{"from":"TWwCRQRZ2ZHMJFn9TzLp7W"},"type":"0"},"txnMetadata":{"seqNo":4,"txnId":"aa5e817d7cc626170eca175822029339a444eb0ee8f0bd20d3b0b76e566fb008"},"ver":"1"}\n', '--webhook-url', 'http://localhost:8032/webhooks', '--trace-target', 'log', '--trace-tag', 'acapy.events', '--trace-label', 'alice.agent.trace', '--auto-accept-invites', '--auto-accept-requests', '--auto-store-credential']
Alice      | 
Alice      | ::::::::::::::::::::::::::::::::::::::::::::::
Alice      | :: alice.agent                              ::
Alice      | ::                                          ::
Alice      | ::                                          ::
Alice      | :: Inbound Transports:                      ::
Alice      | ::                                          ::
Alice      | ::   - http://0.0.0.0:8030                  ::
Alice      | ::                                          ::
Alice      | :: Outbound Transports:                     ::
Alice      | ::                                          ::
Alice      | ::   - http                                 ::
Alice      | ::   - https                                ::
Alice      | ::                                          ::
Alice      | :: Administration API:                      ::
Alice      | ::                                          ::
Alice      | ::   - http://0.0.0.0:8031                  ::
Alice      | ::                                          ::
Alice      | ::                               ver: 0.7.1 ::
Alice      | ::::::::::::::::::::::::::::::::::::::::::::::
Alice      | 
Alice      | Listening...
Alice      | 
Startup duration: 9.08s
Admin URL is at: http://127.0.0.1:8031
Endpoint URL is at: http://ip10-2-63-4-c50v5b9da8909vr6b89g-8030.direct.play-with-von.vonx.io

#9 Input faber.py invitation details
Invite details: https://agentbook.vonx.io:10000?c_i=eyJyZWNpcGllbnRLZXlzIjogWyI4WVhkRDhTSFA2dmNXaE5rOHVkUXpKbTdNOVB5WjhjMnA5NGU5VG9nQ1pzai
JdLCAicm91dGluZ0tleXMiOiBbXSwgInNlcnZpY2VFbmRwb2ludCI6ICJodHRwczovL2FnZW50Ym9vay52b254LmlvOjEwMDAwIiwgImxhYmVsIjogIkFnZW50Qm9vayIsICJAaWQi
OiAiMTc4YmM1YWYtMjhmMS00MjU0LTk1N2ItMmQzODhmODM0ZDM3IiwgIkB0eXBlIjogImRpZDpzb3Y6QnpDYnNOWWhNcmpIaXFaRFRVQVNIZztzcGVjL2Nvbm5lY3Rpb25zLzEuMC
9pbnZpdGF0aW9uIn0=                                                                                                                        
alice.agent handle_connections invitation invitation-received
alice.agent set connection id 487a9f2e-dd8e-4435-b9c9-0bb9051eda00
alice.agent handle_connections request request-sent
Invitation response:
  {
    "their_role": "inviter",
    "rfc23_state": "request-sent",
    "request_id": "17f6feac-c9de-4238-8814-a881f87460b8",
    "their_label": "AgentBook",
    "routing_state": "none",
    "updated_at": "2021-09-15 13:22:07.109616Z",
    "state": "request",
    "created_at": "2021-09-15 13:22:07.056969Z",
    "my_did": "BDWvtWWxGrNm9Xjs1tvREt",
    "accept": "auto",
    "invitation_key": "8YXdD8SHP6vcWhNk8udQzJm7M9PyZ8c2p94e9TogCZsj",
    "invitation_msg_id": "178bc5af-28f1-4254-957b-2d388f834d37",
    "connection_id": "487a9f2e-dd8e-4435-b9c9-0bb9051eda00",
    "connection_protocol": "connections/1.0",
    "invitation_mode": "once"
  }
  
Connect duration: 0.13s
Waiting for connection...
Alice      | 2021-09-15 13:22:07,241 aries_cloudagent.transport.outbound.manager ERROR >>> Error when posting to: https://agentbook.vonx.io:10000; Error: (<class 'aries_cloudagent.transport.outbound.base.OutboundTransportError'>, OutboundTransportError('Unexpected response status 400, caused by: Bad Request',), <traceback object at 0x7f094dd51748>); Re-queue failed message ...
Alice      | 2021-09-15 13:22:17,266 aries_cloudagent.transport.outbound.manager ERROR >>> Error when posting to: https://agentbook.vonx.io:10000; Error: (<class 'aries_cloudagent.transport.outbound.base.OutboundTransportError'>, OutboundTransportError('Unexpected response status 400, caused by: Bad Request',), <traceback object at 0x7f094d7dcbc8>); Re-queue failed message ...
Alice      | 2021-09-15 13:22:27,331 aries_cloudagent.transport.outbound.manager ERROR >>> Error when posting to: https://agentbook.vonx.io:10000; Error: (<class 'aries_cloudagent.transport.outbound.base.OutboundTransportError'>, OutboundTransportError('Unexpected response status 400, caused by: Bad Request',), <traceback object at 0x7f095c1e33c8>); Re-queue failed message ...
Alice      | 2021-09-15 13:22:37,395 aries_cloudagent.transport.outbound.manager ERROR >>> Error when posting to: https://agentbook.vonx.io:10000; Error: (<class 'aries_cloudagent.transport.outbound.base.OutboundTransportError'>, OutboundTransportError('Unexpected response status 400, caused by: Bad Request',), <traceback object at 0x7f094dd51248>); Re-queue failed message ...
Alice      | 2021-09-15 13:22:47,456 aries_cloudagent.transport.outbound.manager ERROR >>> Outbound message failed to deliver, NOT Re-queued.
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/aries_cloudagent/transport/outbound/http.py", line 86, in handle_message
Alice      |     f"Unexpected response status {response.status}, "
Alice      | aries_cloudagent.transport.outbound.base.OutboundTransportError: Unexpected response status 400, caused by: Bad Request
Alice      | 2021-09-15 13:22:47,457 aries_cloudagent.transport.outbound.manager ERROR Outbound message could not be delivered to https://agentbook.vonx.io:10000
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/aries_cloudagent/transport/outbound/http.py", line 86, in handle_message
Alice      |     f"Unexpected response status {response.status}, "
Alice      | aries_cloudagent.transport.outbound.base.OutboundTransportError: Unexpected response status 400, caused by: Bad Request
```

---

3. I also tried to run demo locally. I got similar error. I thought that maybe the problem is that my local endpoint cannot be called by Vonx.io. By reading code I figured out that maybe I should use ngrok. I set up port piping to 8030 and tried again. No win. I got similar error: 400 bad_request.

---

4. I tried to check out if there is something wrong by reading code and tried to run demo locally. 

Unfortunately I'm not skilled python and failed to figure out what goes wrong. I found out, whatsoever, that I need to install pyyaml and aiohttp, otherwise my IDE (PyCharm) tells that I have missing imports. I'm not sure if this is bug, I.e. should these libraries be in requirements.txt

I also noticed that trere seems to be some kind of support for debugging with PyCharm. However, as this was my first lab, I'm not fluent with Python and this is the first time I use PyCharm, so I decided to just write this issue for now and hope that there is an easy to fix bug in the lab.

--

5. At last, I tried to run test to validate to get more tips what is wrong. I run

```
LEDGER_URL=http://dev.bcovrin.vonx.io ./run_bdd
```
 
After the test were run, here's the results: 
```
1 feature passed, 3 failed, 0 skipped
22 scenarios passed, 11 failed, 0 skipped
198 steps passed, 11 failed, 43 skipped, 0 undefined
```

---

It seems to me the the demo is somehow broken at the moment. The lab it self was nice, too bad that it does not work at the moment for me. Any tips how to make it work are welcome.

**Comment by ilmirajat** [comment]
By reading Dockerfile.demo in https://github.com/hyperledger/aries-cloudagent-python I noticed that I probably should have used ./requirements.txt, instead of ./demo/requirements.txt to install dependencies.

**Comment by swcurran** [comment]
Thanks for the notes -- I'll take a look at the lab and make sure I've got the docs right, either here or in the ACA-Py repo.

**Comment by sal-baybo** [comment]
FYI I am also getting the same error as ilmirajat was in September.  What is the workaround to get this working?
